MAINTAINER=	nervoso@k1.com.br

PKGNAME=	systemfix-1.0
CATEGORIES=	lzt

COMMENT=	Meta-package for various system fixes

META_PACKAGE=	yes
RCD_SCRIPTS=	fixhostname

.include "../../lang/gcc48/buildlink3.mk"
.include "../../mk/bsd.pkg.mk"
